spring.application.name=activos-app

spring.datasource.url=jdbc:postgresql://localhost:5433/activosapp
spring.datasource.username=matias
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect