spring.application.name=activos-app

spring.datasource.url=jdbc:postgresql://localhost:5433/activosapp
spring.datasource.username=matias
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:98e5ddae25671d15c12f4a781e1bc47cf7eb14704c663f03f8a409e92f2bdf62}